#!/bin/bash
### BEGIN INIT INFO
# Provides:          daedalus
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: daedalus
# Description:       daedalus server wizzard startup
### END INIT INFO
ulimit -Hn 1048576
ulimit -Sn 1048576
if [[ $1 = "start" ]]; then
    sudo daedalus startup
elif [[ $1 == "stop" ]]; then
    sudo daedalus shutdown
else
    echo "Invalid command! "$1
fi
